import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, FileText, ShieldCheck, Users } from "lucide-react";
import { AdminPage } from "@/components/admin/admin-ui";
import { createAdminClient } from "@/lib/supabase/admin";

export const metadata:Metadata={title:"Administración de plataforma | Arkad",robots:{index:false,follow:false}};
export default async function PlatformDashboard(){const db=createAdminClient();const [insurers,clients,quotes,products,recent]=await Promise.all([count(db,"aseguradora"),count(db,"cliente"),count(db,"cotizacion"),count(db,"producto"),db.from("aseguradora").select("id,nombre_comercial,razon_social,activo,creado_en").order("creado_en",{ascending:false}).limit(5)]);return <AdminPage eyebrow="Control global" title="Plataforma Arkad" description="Administra la estructura comercial y supervisa la operación completa desde un solo lugar."><section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Building2/>} label="Aseguradoras" value={insurers}/><Metric icon={<Users/>} label="Clientes" value={clients}/><Metric icon={<FileText/>} label="Cotizaciones" value={quotes}/><Metric icon={<ShieldCheck/>} label="Productos" value={products}/></section><section className="glass-panel mt-4 overflow-hidden"><header className="flex items-center justify-between border-b border-white/10 p-5 sm:p-6"><div><h2 className="font-bold">Aseguradoras recientes</h2><p className="mt-1 text-xs text-white/45">Altas registradas en la plataforma</p></div><Link href="/admin/aseguradoras" className="flex min-h-11 items-center gap-2 text-sm font-bold text-cyan-100">Administrar <ArrowRight className="size-4"/></Link></header><div className="divide-y divide-white/8">{(recent.data||[]).map(x=><div key={x.id} className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6"><div><p className="font-semibold">{x.nombre_comercial}</p><p className="mt-1 text-xs text-white/42">{x.razon_social}</p></div><span className={`size-2 rounded-full ${x.activo?"bg-emerald-300":"bg-white/25"}`}/></div>)}</div></section></AdminPage>}
async function count(db:ReturnType<typeof createAdminClient>,table:"aseguradora"|"cliente"|"cotizacion"|"producto"){const{count}=await db.from(table).select("id",{count:"exact",head:true});return count||0}function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <article className="glass-panel p-5"><span className="text-cyan-100 [&_svg]:size-5">{icon}</span><p className="mt-7 text-3xl font-bold tracking-[-0.04em]">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.12em] text-white/42">{label}</p></article>}
