import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AdminPage, AdminPanel } from "@/components/admin/admin-ui";
import { AnnualRateForm, DepreciationForm, MonthlyParametersForm, RiskModelForm, RiskParameterForm, RiskRateForm, VehicleTypeForm } from "@/components/insurer/maintenance-forms";
import { requireInsurerAdmin } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";

export const metadata:Metadata={title:"Parametrización de producto | Arkad",robots:{index:false,follow:false}};
const depreciationTypes=["NUEVO_1ER_ANIO","NUEVO_DESDE_2DO","USADO_1ER_ANIO","USADO_DESDE_2DO"];
const sectionLinks=[["#tasas","Tasas e impuestos"],["#depreciacion","Años y depreciación"],["#riesgos","Factores de riesgo"],["#tarifas","Matriz tarifaria"]] as const;

export default async function ProductConfiguration({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const session=await requireInsurerAdmin(); const db=createAdminClient();
  const {data:product}=await db.from("producto").select("id,nombre").eq("id",id).eq("aseguradora_id",session.insurerId!).maybeSingle(); if(!product)notFound();
  const [types,models,rates,monthly,annual,depreciation,cities,citiesCatalog,genders,uses,amounts,colors,civil,ages,tariffs,losses]=await Promise.all([
    db.from("tipo_vehiculo").select("id,descripcion").eq("producto_id",id).order("descripcion"), db.from("riesgo_modelo").select("id,marca,modelo,nivel_riesgo,justificacion").eq("producto_id",id).order("marca").order("modelo"), db.from("tasa_por_nivel_riesgo").select("id,nivel_riesgo,tasa").eq("producto_id",id).order("nivel_riesgo"), db.from("parametro_modelo_mensual").select("super_bancos_pct,seguro_campesino_pct,derechos_emision_valor,iva_pct").eq("producto_id",id).maybeSingle(), db.from("tasa_anual_producto").select("numero_anio,tasa").eq("producto_id",id).order("numero_anio"), db.from("tabla_depreciacion").select("tipo,porcentaje").eq("producto_id",id), db.from("riesgo_ciudad").select("id,nivel_riesgo,ciudad(nombre)").eq("producto_id",id).order("nivel_riesgo"), db.from("ciudad").select("id,nombre").order("nombre"), db.from("riesgo_genero").select("id,genero,porcentaje_participacion,nivel_riesgo").eq("producto_id",id).order("genero"), db.from("riesgo_uso").select("id,uso,nivel_riesgo").eq("producto_id",id).order("uso"), db.from("riesgo_monto_asegurado").select("id,monto_desde,monto_hasta,nivel_riesgo").eq("producto_id",id).order("monto_desde"), db.from("riesgo_color").select("id,color,nivel_riesgo").eq("producto_id",id).order("color"), db.from("riesgo_estado_civil").select("id,estado_civil,nivel_riesgo").eq("producto_id",id).order("estado_civil"), db.from("riesgo_edad").select("id,edad_desde,edad_hasta,nivel_riesgo").eq("producto_id",id).order("edad_desde"), db.from("tarifa_base").select("id,tiempo_credito,riesgo_marca,riesgo_ciudad,riesgo_genero,riesgo_uso,depreciacion,tasa,tipo_vehiculo(descripcion)").eq("producto_id",id).order("tiempo_credito").limit(500), db.from("tabla_perdidas").select("nivel_riesgo,perdidas_parciales,perdidas_totales").eq("producto_id",id).order("nivel_riesgo")
  ]);
  const annualMap=new Map((annual.data||[]).map(x=>[x.numero_anio,x.tasa])); const depMap=new Map((depreciation.data||[]).map(x=>[x.tipo,x.porcentaje]));
  return <AdminPage eyebrow="Base del cálculo" title={`Parametrización · ${product.nombre}`} description="Todos estos parámetros pertenecen exclusivamente a este producto y su aseguradora. Los porcentajes se guardan como decimales: 0.035 equivale a 3,5%.">
    <details className="glass-panel group mt-7 md:hidden"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between px-4 text-sm font-bold"><span>Ir a una sección</span><span className="text-cyan-100 transition-transform group-open:rotate-45">＋</span></summary><nav className="grid gap-2 border-t border-white/10 p-3" aria-label="Secciones de parametrización móvil">{sectionLinks.map(([href,label],index)=><a key={href} href={href} className="flex min-h-12 items-center gap-3 rounded-xl border border-white/10 bg-white/5 px-4 text-sm font-semibold"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-cyan-100/10 text-xs text-cyan-100">{index+1}</span>{label}</a>)}</nav></details>
    <nav className="glass-panel mt-7 hidden gap-2 p-3 text-xs font-bold md:flex" aria-label="Secciones de parametrización">{sectionLinks.map(([href,label])=><a key={href} href={href} className="rounded-full border border-white/12 px-4 py-2.5 hover:bg-white/8">{label}</a>)}</nav>
    <div className="mt-4 grid gap-4">
      <section id="tasas" className="scroll-mt-4 grid gap-4">
        <AdminPanel title="Escala común de riesgo" description="Convierte la clasificación Alto, Moderado o Bajo de los 8 factores en una tasa para el promedio" open><p className="mb-5 rounded-xl border border-cyan-200/15 bg-cyan-200/6 p-4 text-sm leading-6 text-cyan-50/70">Esta no es la tasa de cada año. Es la escala compartida por marca/modelo, ciudad, género, uso, color, estado civil, edad y monto asegurado.</p><div className="grid gap-3 sm:grid-cols-3">{[1,2,3].map(level=>{const item=(rates.data||[]).find(x=>x.nivel_riesgo===level);return <div key={level} className="rounded-2xl border border-white/10 bg-white/4 p-4"><RiskRateForm productId={id} item={item}/><p className="mt-3 text-center text-xs text-white/45">{levelName(level)}</p></div>})}</div></AdminPanel>
        <AdminPanel title="Impuestos y cargos mensuales" description="Valores aplicados a cada prima mensual: Superintendencia de Bancos, Seguro Campesino, emisión e IVA" open><MonthlyParametersForm productId={id} item={monthly.data||undefined}/><div className="mt-5 grid gap-2 text-xs text-white/55 sm:grid-cols-2"><p>Superintendencia = prima neta × porcentaje</p><p>Seguro Campesino = prima neta × porcentaje</p><p>Subtotal = prima + cargos + emisión</p><p>IVA = subtotal × porcentaje</p></div></AdminPanel>
      </section>
      <section id="depreciacion" className="scroll-mt-4 grid gap-4">
        <AdminPanel title="Tasa correspondiente a cada año" description="El año 1 lo calcula el promedio de riesgo; la aseguradora configura manualmente los años 2 al 5" open><div className="mb-4 rounded-2xl border border-cyan-200/15 bg-cyan-200/6 p-4"><p className="text-xs font-bold uppercase tracking-wider text-cyan-100/60">Año 1</p><p className="mt-1 font-semibold">Calculada automáticamente al cotizar</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[2,3,4,5].map(year=><div key={year} className="rounded-2xl border border-white/10 bg-white/4 p-4"><AnnualRateForm productId={id} year={year} rate={annualMap.get(year)}/></div>)}</div></AdminPanel>
        <AdminPanel title="Depreciación anual" description="Porcentaje según estado del vehículo y período de vigencia" open><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{depreciationTypes.map(type=><div key={type} className="rounded-2xl border border-white/10 bg-white/4 p-4"><DepreciationForm productId={id} type={type} percentage={depMap.get(type)}/></div>)}</div></AdminPanel>
      </section>
      <section id="riesgos" className="scroll-mt-4 grid gap-4">
        <AdminPanel title={`Riesgo · Marcas y modelos (${models.data?.length||0})`} description="Cada modelo se clasifica como Alto, Moderado o Bajo; luego usa la escala común de tasas" open><RiskModelForm productId={id}/><DataTable headers={["Marca","Modelo","Clasificación"]} rows={(models.data||[]).map(x=>[x.marca,x.modelo,levelName(x.nivel_riesgo)])}/></AdminPanel>
        <AdminPanel title={`Riesgo · Ciudades (${cities.data?.length||0})`} description="Clasificación territorial"><RiskParameterForm kind="ciudad" productId={id} cities={citiesCatalog.data||[]}/><DataTable headers={["Ciudad","Clasificación"]} rows={(cities.data||[]).map(x=>[relation(x.ciudad,"nombre"),levelName(x.nivel_riesgo)])}/></AdminPanel>
        <AdminPanel title={`Riesgo · Género (${genders.data?.length||0})`} description="Participación y clasificación"><RiskParameterForm kind="genero" productId={id}/><DataTable headers={["Género","Participación","Clasificación"]} rows={(genders.data||[]).map(x=>[x.genero,`${Number(x.porcentaje_participacion||0)}%`,levelName(x.nivel_riesgo)])}/></AdminPanel>
        <AdminPanel title={`Riesgo · Uso del vehículo (${uses.data?.length||0})`} description="Comercial, particular o corporativo"><RiskParameterForm kind="uso" productId={id}/><DataTable headers={["Uso","Clasificación"]} rows={(uses.data||[]).map(x=>[x.uso,levelName(x.nivel_riesgo)])}/></AdminPanel>
        <div className="grid gap-4 xl:grid-cols-2"><AdminPanel title={`Riesgo · Colores (${colors.data?.length||0})`}><RiskParameterForm kind="color" productId={id}/><DataTable headers={["Color","Clasificación"]} rows={(colors.data||[]).map(x=>[x.color,levelName(x.nivel_riesgo)])}/></AdminPanel><AdminPanel title={`Riesgo · Estado civil (${civil.data?.length||0})`}><RiskParameterForm kind="estado_civil" productId={id}/><DataTable headers={["Estado civil","Clasificación"]} rows={(civil.data||[]).map(x=>[x.estado_civil,levelName(x.nivel_riesgo)])}/></AdminPanel></div>
        <div className="grid gap-4 xl:grid-cols-2"><AdminPanel title={`Riesgo · Rangos de edad (${ages.data?.length||0})`}><RiskParameterForm kind="edad" productId={id}/><DataTable headers={["Desde","Hasta","Clasificación"]} rows={(ages.data||[]).map(x=>[String(x.edad_desde),x.edad_hasta==null?"Sin límite":String(x.edad_hasta),levelName(x.nivel_riesgo)])}/></AdminPanel><AdminPanel title={`Riesgo · Monto asegurado (${amounts.data?.length||0})`}><RiskParameterForm kind="monto" productId={id}/><DataTable headers={["Desde","Hasta","Clasificación"]} rows={(amounts.data||[]).map(x=>[money(x.monto_desde),x.monto_hasta==null?"Sin límite":money(x.monto_hasta),levelName(x.nivel_riesgo)])}/></AdminPanel></div>
      </section>
      <section id="tarifas" className="scroll-mt-4 grid gap-4">
        <AdminPanel title={`Tipos de vehículo (${types.data?.length||0})`} description="Primera dimensión de la matriz tarifaria"><VehicleTypeForm productId={id}/><DataTable headers={["Tipo de vehículo"]} rows={(types.data||[]).map(x=>[x.descripcion])}/></AdminPanel>
        <AdminPanel title={`Matriz tarifaria (${tariffs.data?.length||0})`} description="Tasa propia por tipo de vehículo, vigencia y combinación de niveles de riesgo" open>
          <div className="rounded-2xl border border-cyan-200/15 bg-cyan-200/6 p-4 text-sm leading-6 text-cyan-50/70"><p className="font-bold text-cyan-50">Cómo leer esta matriz</p><p className="mt-1">Las columnas no identifican una marca, ciudad, género o uso específico. Indican su clasificación: Alto, Moderado o Bajo. Por ejemplo, todas las ciudades clasificadas como Moderado utilizan las filas con “Moderado (2)”.</p></div>
          <div className="mt-4 grid gap-3 xl:grid-cols-2">{[1,2,3].map(level=><article key={level} className="rounded-2xl border border-white/10 bg-white/4 p-4"><p className="text-xs font-bold uppercase tracking-wider text-cyan-100/65">{levelName(level)} ({level})</p><dl className="mt-3 grid gap-2 text-xs"><Legend label="Marcas / modelos" values={(models.data||[]).filter(x=>x.nivel_riesgo===level).map(x=>`${x.marca} ${x.modelo}`)}/><Legend label="Ciudades" values={(cities.data||[]).filter(x=>x.nivel_riesgo===level).map(x=>relation(x.ciudad,"nombre"))}/><Legend label="Género" values={(genders.data||[]).filter(x=>x.nivel_riesgo===level).map(x=>x.genero)}/><Legend label="Uso" values={(uses.data||[]).filter(x=>x.nivel_riesgo===level).map(x=>x.uso)}/></dl></article>)}</div>
          <DataTable compact headers={["Tipo","Vigencia","R. marca","R. ciudad","R. género","R. uso","Deprec.","Tasa"]} rows={(tariffs.data||[]).map(x=>[relation(x.tipo_vehiculo,"descripcion"),x.tiempo_credito,levelWithNumber(x.riesgo_marca),levelWithNumber(x.riesgo_ciudad),levelWithNumber(x.riesgo_genero),levelWithNumber(x.riesgo_uso),percent(x.depreciacion),percent(x.tasa)])}/>
        </AdminPanel>
        <AdminPanel title={`Deducibles por pérdidas (${losses.data?.length||0})`} description="Condiciones de pérdidas parciales y totales según nivel"><DataTable headers={["Nivel","Pérdidas parciales","Pérdidas totales"]} rows={(losses.data||[]).map(x=>[levelName(x.nivel_riesgo),x.perdidas_parciales,x.perdidas_totales])}/></AdminPanel>
      </section>
    </div>
  </AdminPage>;
}

function DataTable({headers,rows,compact=false}:{headers:string[];rows:string[][];compact?:boolean}){return <div className="mt-5 min-w-0 max-w-full overflow-hidden rounded-2xl border border-white/10"><div className="grid gap-0 divide-y divide-white/8 md:hidden">{rows.map((row,i)=><article key={i} className="grid min-w-0 gap-2 bg-white/[0.025] p-4">{row.map((value,j)=><div key={j} className="grid min-w-0 grid-cols-[minmax(82px,34%)_minmax(0,1fr)] gap-3 text-xs"><span className="break-words font-bold uppercase tracking-[0.06em] text-white/38">{headers[j]}</span><span className="min-w-0 break-words text-right leading-5 text-white/72">{value}</span></div>)}</article>)}{!rows.length&&<p className="p-5 text-center text-sm text-white/45">Sin registros</p>}</div><table className={`hidden w-full table-fixed text-left md:table ${compact?"text-[11px]":"text-xs xl:text-sm"}`}><thead className="bg-white/5 text-[10px] uppercase tracking-wider text-white/45"><tr>{headers.map((x,i)=><th key={x} className={`break-words px-2 py-2.5 xl:px-3 ${compact&&i===0?"w-[23%]":compact&&i===1?"w-[13%]":""}`}>{x}</th>)}</tr></thead><tbody className="divide-y divide-white/8">{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j} className="break-words px-2 py-2.5 leading-5 text-white/70 xl:px-3">{x}</td>)}</tr>)}</tbody></table></div>}
function Legend({label,values}:{label:string;values:string[]}){const unique=[...new Set(values)];return <div className="grid grid-cols-[105px_1fr] gap-2"><dt className="font-semibold text-white/42">{label}</dt><dd className="text-white/68">{unique.length?`${unique.slice(0,5).join(", ")}${unique.length>5?` y ${unique.length-5} más`:""}`:"Sin registros"}</dd></div>}
function levelName(level:number){return level===1?"Alto":level===2?"Moderado":"Bajo"}function levelWithNumber(level:number){return `${levelName(level)} (${level})`}function relation(value:unknown,key:string){const row=Array.isArray(value)?value[0]:value;return row&&typeof row==="object"&&key in row?String((row as Record<string,unknown>)[key]):"—"}function percent(value:number|string|null){return value==null?"—":`${(Number(value)*100).toLocaleString("es-EC",{maximumFractionDigits:4})}%`}function money(value:number|string){return new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(Number(value))}
