"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireChannelUser } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { createSelfServiceQuote, QuoteConfigurationError } from "@/lib/quotes/create-quote";
import type { ChannelActionState } from "@/lib/channel/action-state";
import type { QuoteActionState } from "@/lib/quotes/types";

const clientSchema=z.object({name:z.string().trim().min(3).max(160),identification:z.string().trim().regex(/^\d{10}(\d{3})?$/,"Ingresa una cédula de 10 dígitos o RUC de 13."),email:z.string().trim().toLowerCase().email(),phone:z.string().trim().min(7).max(20),cityId:z.string().uuid(),birthDate:z.string().date(),gender:z.enum(["HOMBRE","MUJER"]),maritalStatus:z.string().trim().min(2).max(50),address:z.string().trim().max(300).optional()});
export async function saveAssistedClient(_:ChannelActionState,formData:FormData):Promise<ChannelActionState>{const session=await requireChannelUser();const parsed=clientSchema.safeParse({name:formData.get("name"),identification:formData.get("identification"),email:formData.get("email"),phone:formData.get("phone"),cityId:formData.get("cityId"),birthDate:formData.get("birthDate"),gender:formData.get("gender"),maritalStatus:formData.get("maritalStatus"),address:formData.get("address")||""});if(!parsed.success)return{status:"error",message:"Revisa los datos del cliente.",fields:parsed.error.flatten().fieldErrors as Record<string,string[]>};const db=createAdminClient();const{data:existing}=await db.from("cliente").select("id,nombre_razon_social,email,identificacion").or(`identificacion.eq.${parsed.data.identification},email.ilike.${parsed.data.email}`).limit(1).maybeSingle();let clientId=existing?.id;if(!clientId){const{data,error}=await db.from("cliente").insert({tipo_cliente:"INDIVIDUAL",nombre_razon_social:parsed.data.name,identificacion:parsed.data.identification,email:parsed.data.email,password_hash:null,telefono:parsed.data.phone,ciudad_id:parsed.data.cityId,direccion:parsed.data.address||null,fecha_nacimiento:parsed.data.birthDate,genero:parsed.data.gender,estado_civil:parsed.data.maritalStatus.toUpperCase(),activo:true,estado_registro:"SIN_ACCESO"}).select("id").single();if(error)return{status:"error",message:error.code==="23505"?"Ya existe un cliente con esa identificación o correo.":"No pudimos registrar al cliente."};clientId=data.id;}const{error:linkError}=await db.from("canal_cliente").upsert({canal_id:session.channelId!,cliente_id:clientId,creado_por_usuario_id:session.actorId},{onConflict:"canal_id,cliente_id"});if(linkError)return{status:"error",message:"El cliente existe, pero no pudimos vincularlo con el canal."};await db.from("auditoria").insert({entidad:existing?"CANAL_CLIENTE":"CLIENTE",entidad_id:clientId,accion:"CREACION",datos_nuevos:{canal_id:session.channelId,origen:"CANAL",cliente_nuevo:!existing},usuario_id:session.actorId});revalidatePath("/canal/clientes");return{status:"success",message:existing?`Cliente existente vinculado: ${existing.nombre_razon_social}.`:"Cliente registrado y vinculado correctamente.",clientId};}

export async function linkExistingClient(formData:FormData){const session=await requireChannelUser();const parsed=z.object({clientId:z.string().uuid(),identification:z.string().min(5)}).safeParse({clientId:formData.get("clientId"),identification:formData.get("identification")});if(!parsed.success)return;const db=createAdminClient();const{data}=await db.from("cliente").select("id").eq("id",parsed.data.clientId).eq("identificacion",parsed.data.identification).maybeSingle();if(data)await db.from("canal_cliente").upsert({canal_id:session.channelId!,cliente_id:data.id,creado_por_usuario_id:session.actorId},{onConflict:"canal_id,cliente_id"});revalidatePath("/canal/clientes");redirect(`/canal/cotizaciones/nueva?cliente=${parsed.data.clientId}`);}

const quoteSchema=z.object({clientId:z.string().uuid(),productId:z.string().uuid(),vehicleMode:z.enum(["new","existing"]),existingVehicleId:z.string().uuid().optional().or(z.literal("")),vehicleTypeId:z.string().uuid().optional().or(z.literal("")),brand:z.string().trim().max(80).optional(),model:z.string().trim().max(80).optional(),year:z.coerce.number().int().min(1950).max(new Date().getFullYear()+1).optional(),color:z.string().trim().max(50).optional(),insuredValue:z.coerce.number().positive().max(5_000_000).optional(),vehicleStatus:z.enum(["NUEVO","USADO"]).optional(),use:z.enum(["COMERCIAL","PARTICULAR","CORPORATIVO"]).optional(),plate:z.string().trim().max(15).optional(),durationYears:z.coerce.number().int().min(1).max(5),startDate:z.string().date(),coverageIds:z.array(z.string().uuid()).min(1,"Selecciona al menos una cobertura.")}).superRefine((d,c)=>{if(d.vehicleMode==="existing"&&!d.existingVehicleId)c.addIssue({code:"custom",path:["existingVehicleId"],message:"Selecciona un vehículo."});if(d.vehicleMode==="new")for(const field of ["vehicleTypeId","brand","model","year","color","insuredValue","vehicleStatus","use"] as const)if(d[field]===undefined||d[field]==="")c.addIssue({code:"custom",path:[field],message:"Este campo es obligatorio."});const today=dateOnly(new Date()),max=dateOnly(new Date(Date.now()+90*86400000));if(d.startDate<today||d.startDate>max)c.addIssue({code:"custom",path:["startDate"],message:"La fecha debe estar entre hoy y los próximos 90 días."});});
export async function createAssistedQuote(_:QuoteActionState,formData:FormData):Promise<QuoteActionState>{const session=await requireChannelUser();const parsed=quoteSchema.safeParse({clientId:formData.get("clientId"),productId:formData.get("productId"),vehicleMode:formData.get("vehicleMode"),existingVehicleId:formData.get("existingVehicleId")||"",vehicleTypeId:formData.get("vehicleTypeId")||"",brand:formData.get("brand")||"",model:formData.get("model")||"",year:formData.get("year")||undefined,color:formData.get("color")||"",insuredValue:formData.get("insuredValue")||undefined,vehicleStatus:formData.get("vehicleStatus")||undefined,use:formData.get("use")||undefined,plate:formData.get("plate")||"",durationYears:formData.get("durationYears"),startDate:formData.get("startDate"),coverageIds:formData.getAll("coverageIds")});if(!parsed.success)return{status:"error",message:"Revisa los datos indicados para continuar.",fields:parsed.error.flatten().fieldErrors as Record<string,string[]>};let quoteId:string;try{quoteId=await createSelfServiceQuote({clientId:parsed.data.clientId,productId:parsed.data.productId,existingVehicleId:parsed.data.vehicleMode==="existing"?parsed.data.existingVehicleId||undefined:undefined,vehicleTypeId:parsed.data.vehicleTypeId||undefined,brand:parsed.data.brand,model:parsed.data.model,year:parsed.data.year,color:parsed.data.color,insuredValue:parsed.data.insuredValue,vehicleStatus:parsed.data.vehicleStatus,use:parsed.data.use,plate:parsed.data.plate,durationYears:parsed.data.durationYears,coverageIds:[...new Set(parsed.data.coverageIds)],coverageStartDate:parsed.data.startDate,assistedBy:{userId:session.actorId,insurerId:session.insurerId!,channelId:session.channelId!}});}catch(error){console.error("Error al crear cotización asistida",error);return{status:"error",message:error instanceof QuoteConfigurationError?error.message:"No pudimos calcular la cotización. No se guardó ningún dato."};}redirect(`/canal/cotizaciones/${quoteId}?created=1`);}
function dateOnly(date:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Guayaquil",year:"numeric",month:"2-digit",day:"2-digit"}).format(date)}
