"use client";

import { useActionState } from "react";
import { LoaderCircle, Save } from "lucide-react";
import { saveAnnualRate, saveChannel, saveChannelUser, saveDepreciation, saveMonthlyParameters, saveProduct, saveRiskModel, saveRiskParameter, saveRiskRate, saveVehicleType } from "@/app/actions/insurer";
import { initialInsurerState } from "@/lib/insurer/action-state";

const input="min-h-11 min-w-0 max-w-full w-full rounded-xl border border-white/15 bg-[#061323]/65 px-3.5 text-sm text-white outline-none placeholder:text-white/30 focus:border-cyan-100/55 [color-scheme:dark]";
type Channel={id:string;nombre:string;descripcion:string|null};

export function ChannelForm({item}:{item?:Channel}){const[state,action,pending]=useActionState(saveChannel,initialInsurerState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nombre"><input name="name" required defaultValue={item?.nombre} className={input}/></Field><Field label="Descripción"><input name="description" defaultValue={item?.descripcion||""} className={input}/></Field></Grid></Form>}
export function ProductForm({channels,branches,item}:{channels:{id:string;nombre:string}[];branches:{id:string;name:string}[];item?:{id:string;nombre:string;canal_id:string;aseguradora_ramo_id:string;aplica_todas_ciudades:boolean}}){const[state,action,pending]=useActionState(saveProduct,initialInsurerState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nombre del producto"><input name="name" required defaultValue={item?.nombre} className={input}/></Field><Field label="Canal"><select name="channelId" required defaultValue={item?.canal_id||""} className={input}><option value="">Selecciona</option>{channels.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field><Field label="Ramo habilitado"><select name="branchId" required defaultValue={item?.aseguradora_ramo_id||""} className={input}><option value="">Selecciona</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><label className="flex min-h-11 items-center gap-3 rounded-xl border border-white/12 bg-white/5 px-4 text-sm font-semibold"><input name="allCities" type="checkbox" defaultChecked={item?.aplica_todas_ciudades??true} className="size-4 accent-cyan-200"/>Aplica a todas las ciudades</label></Grid></Form>}
export function ChannelUserForm({channels,item}:{channels:{id:string;nombre:string}[];item?:{id:string;nombre:string;email:string;canal_id:string}}){const[state,action,pending]=useActionState(saveChannelUser,initialInsurerState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nombre"><input name="name" required defaultValue={item?.nombre} className={input}/></Field><Field label="Correo"><input name="email" type="email" required defaultValue={item?.email} className={input}/></Field><Field label="Canal"><select name="channelId" required defaultValue={item?.canal_id||""} className={input}><option value="">Selecciona</option>{channels.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field><Field label={item?"Nueva contraseña (opcional)":"Contraseña temporal"}><input name="password" type="password" minLength={10} required={!item} autoComplete="new-password" className={input}/></Field></Grid></Form>}
export function VehicleTypeForm({productId,item}:{productId:string;item?:{id:string;descripcion:string}}){const[state,action,pending]=useActionState(saveVehicleType,initialInsurerState);return <Form action={action} state={state} pending={pending} compact><input type="hidden" name="productId" value={productId}/><input type="hidden" name="id" value={item?.id||""}/><Field label="Tipo de vehículo"><input name="description" required defaultValue={item?.descripcion} placeholder="Ej. Livianos particulares" className={input}/></Field></Form>}
export function RiskModelForm({productId,item}:{productId:string;item?:{id:string;marca:string;modelo:string;nivel_riesgo:number;justificacion:string|null}}){const[state,action,pending]=useActionState(saveRiskModel,initialInsurerState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="productId" value={productId}/><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Marca"><input name="brand" required defaultValue={item?.marca} className={input}/></Field><Field label="Modelo"><input name="model" required defaultValue={item?.modelo} className={input}/></Field><Field label="Nivel de riesgo"><select name="level" defaultValue={item?.nivel_riesgo||2} className={input}><option value="1">1 · Alto</option><option value="2">2 · Moderado</option><option value="3">3 · Bajo</option></select></Field><Field label="Justificación"><input name="justification" defaultValue={item?.justificacion||""} className={input}/></Field></Grid></Form>}
export function RiskRateForm({productId,item}:{productId:string;item?:{id:string;nivel_riesgo:number;tasa:number|string}}){const[state,action,pending]=useActionState(saveRiskRate,initialInsurerState);return <Form action={action} state={state} pending={pending} compact><input type="hidden" name="productId" value={productId}/><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nivel"><select name="level" defaultValue={item?.nivel_riesgo||1} className={input}><option value="1">1 · Alto</option><option value="2">2 · Moderado</option><option value="3">3 · Bajo</option></select></Field><Field label="Tasa decimal"><input name="rate" type="number" min="0" max="1" step="0.000001" required defaultValue={item?.tasa??""} placeholder="0.035" className={input}/></Field></Grid></Form>}
export function MonthlyParametersForm({productId,item}:{productId:string;item?:{super_bancos_pct:number|string;seguro_campesino_pct:number|string;derechos_emision_valor:number|string;iva_pct:number|string}}){const[state,action,pending]=useActionState(saveMonthlyParameters,initialInsurerState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="productId" value={productId}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PercentField name="bank" label="Superintendencia de Bancos" value={item?.super_bancos_pct}/><PercentField name="rural" label="Seguro Campesino" value={item?.seguro_campesino_pct}/><Field label="Derechos de emisión (USD)"><input name="issuance" type="number" min="0" step="0.01" required defaultValue={item?.derechos_emision_valor??0.5} className={input}/></Field><PercentField name="vat" label="IVA" value={item?.iva_pct}/></div></Form>}
export function AnnualRateForm({productId,year,rate}:{productId:string;year:number;rate?:number|string}){const[state,action,pending]=useActionState(saveAnnualRate,initialInsurerState);return <Form action={action} state={state} pending={pending} compact><input type="hidden" name="productId" value={productId}/><input type="hidden" name="year" value={year}/><Field label={`Tasa año ${year} (decimal)`}><input name="rate" type="number" min="0" max="1" step="0.000001" required defaultValue={rate??""} placeholder="0.0352" className={input}/></Field></Form>}
export function DepreciationForm({productId,type,percentage}:{productId:string;type:string;percentage?:number|string}){const[state,action,pending]=useActionState(saveDepreciation,initialInsurerState);return <Form action={action} state={state} pending={pending} compact><input type="hidden" name="productId" value={productId}/><input type="hidden" name="type" value={type}/><PercentField name="percentage" label={depreciationLabel(type)} value={percentage}/></Form>}
type RiskKind="ciudad"|"genero"|"uso"|"color"|"estado_civil"|"edad"|"monto";
export function RiskParameterForm({kind,productId,cities}:{kind:RiskKind;productId:string;cities?:{id:string;nombre:string}[]}){const bound=saveRiskParameter.bind(null,kind);const[state,action,pending]=useActionState(bound,initialInsurerState);return <Form action={action} state={state} pending={pending} compact><input type="hidden" name="productId" value={productId}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kind==="ciudad"&&<Field label="Ciudad"><select name="cityId" required className={input}><option value="">Selecciona</option>{cities?.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field>}{kind==="genero"&&<><Field label="Género"><select name="value" className={input}><option>HOMBRE</option><option>MUJER</option></select></Field><Field label="Participación (%)"><input name="participation" type="number" min="0" max="100" step="0.01" required className={input}/></Field></>}{kind==="uso"&&<Field label="Uso"><select name="value" className={input}><option>COMERCIAL</option><option>PARTICULAR</option><option>CORPORATIVO</option></select></Field>}{(kind==="color"||kind==="estado_civil")&&<Field label={kind==="color"?"Color":"Estado civil"}><input name="value" required className={input}/></Field>}{(kind==="edad"||kind==="monto")&&<><Field label={kind==="edad"?"Edad desde":"Monto desde (USD)"}><input name="from" type="number" min="0" required className={input}/></Field><Field label={kind==="edad"?"Edad hasta":"Monto hasta (vacío = sin límite)"}><input name="to" type="number" min="0" className={input}/></Field></>}<RiskLevel/></div></Form>}
function RiskLevel(){return <Field label="Clasificación"><select name="level" defaultValue="2" className={input}><option value="1">Alto</option><option value="2">Moderado</option><option value="3">Bajo</option></select></Field>}
function PercentField({name,label,value}:{name:string;label:string;value?:number|string}){return <Field label={`${label} (decimal)`}><input name={name} type="number" min="0" max="1" step="0.0001" required defaultValue={value??""} placeholder="Ej. 0.035 = 3,5%" className={input}/></Field>}
function depreciationLabel(type:string){return({NUEVO_1ER_ANIO:"Nuevo · primer año",NUEVO_DESDE_2DO:"Nuevo · desde segundo año",USADO_1ER_ANIO:"Usado · primer año",USADO_DESDE_2DO:"Usado · desde segundo año"} as Record<string,string>)[type]||type}
function Form({action,state,pending,children,compact=false}:{action:(formData:FormData)=>void;state:{status:string;message?:string};pending:boolean;children:React.ReactNode;compact?:boolean}){return <form action={action} className="grid min-w-0 max-w-full gap-4">{state.message&&<p className={`max-w-full break-words rounded-xl border px-4 py-3 text-sm ${state.status==="success"?"border-emerald-300/25 bg-emerald-300/10 text-emerald-50":"border-red-300/25 bg-red-300/10 text-red-50"}`}>{state.message}</p>}{children}<button disabled={pending} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-[#071426] hover:opacity-90 disabled:opacity-60 ${compact?"sm:justify-self-start":"sm:justify-self-end"}`}>{pending?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}{pending?"Guardando…":"Guardar"}</button></form>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid min-w-0 gap-4 sm:grid-cols-2">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block min-w-0 max-w-full"><span className="mb-1.5 block break-words text-xs font-bold uppercase tracking-[0.1em] text-white/48">{label}</span>{children}</label>}
