import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, DollarSign, FileCheck2, FileText, Percent, TriangleAlert } from "lucide-react";
import { AdminPage } from "@/components/admin/admin-ui";
import { ComparisonChart, StatusChart } from "@/components/insurer/dashboard-charts";
import { requireInsurerAdmin } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { getDbPool } from "@/lib/db/pool";

export const metadata:Metadata={title:"Administración de aseguradora | Arkad",robots:{index:false,follow:false}};
type MonthlyRow={label:string;quotes:string;policies:string}; type CollectionRow={label:string;billed:string;paid:string}; type StatusRow={label:string;value:string};
type KpiRow={quotes:string;accepted:string;policies:string;billed:string;paid:string;overdue:string};

export default async function Dashboard(){
  const session=await requireInsurerAdmin(); const insurerId=session.insurerId!; const db=createAdminClient(); const pool=getDbPool();
  const [insurer,recent,monthly,collection,statuses,kpis]=await Promise.all([
    db.from("aseguradora").select("nombre_comercial").eq("id",insurerId).single(),
    db.from("cotizacion").select("id,creado_en,estado,cuota_fija_mensual,cliente(nombre_razon_social),producto(nombre)").eq("aseguradora_id",insurerId).order("creado_en",{ascending:false}).limit(5),
    pool.query<MonthlyRow>(`with months as (select generate_series(date_trunc('month',current_date)-interval '5 months',date_trunc('month',current_date),interval '1 month') m), q as (select date_trunc('month',creado_en) m,count(*) n from cotizacion where aseguradora_id=$1 group by 1), p as (select date_trunc('month',p.fecha_emision) m,count(*) n from poliza p join cotizacion c on c.id=p.cotizacion_id where c.aseguradora_id=$1 group by 1) select to_char(months.m,'Mon') label,coalesce(q.n,0)::text quotes,coalesce(p.n,0)::text policies from months left join q using(m) left join p using(m) order by months.m`,[insurerId]),
    pool.query<CollectionRow>(`with months as (select generate_series(date_trunc('month',current_date)-interval '5 months',date_trunc('month',current_date),interval '1 month') m), payments as (select cobranza_id,sum(monto_pagado) filter(where estado='REGISTRADO') paid from pago group by cobranza_id), totals as (select date_trunc('month',t.fecha_vencimiento) m,sum(t.monto) billed,sum(coalesce(pg.paid,0)) paid from tabla_cobranza t join poliza p on p.id=t.poliza_id join cotizacion c on c.id=p.cotizacion_id left join payments pg on pg.cobranza_id=t.id where c.aseguradora_id=$1 group by 1) select to_char(months.m,'Mon') label,coalesce(t.billed,0)::text billed,coalesce(t.paid,0)::text paid from months left join totals t using(m) order by months.m`,[insurerId]),
    pool.query<StatusRow>(`select estado label,count(*)::text value from cotizacion where aseguradora_id=$1 group by estado order by count(*) desc`,[insurerId]),
    pool.query<KpiRow>(`with pay as (select cobranza_id,sum(monto_pagado) filter(where estado='REGISTRADO') paid from pago group by cobranza_id), col as (select coalesce(sum(t.monto),0) billed,coalesce(sum(pg.paid),0) paid,coalesce(sum(t.monto) filter(where t.estado='VENCIDO'),0) overdue from tabla_cobranza t join poliza p on p.id=t.poliza_id join cotizacion c on c.id=p.cotizacion_id left join pay pg on pg.cobranza_id=t.id where c.aseguradora_id=$1) select (select count(*) from cotizacion where aseguradora_id=$1)::text quotes,(select count(*) from cotizacion where aseguradora_id=$1 and estado='ACEPTADA')::text accepted,(select count(*) from poliza p join cotizacion c on c.id=p.cotizacion_id where c.aseguradora_id=$1)::text policies,col.billed::text,col.paid::text,col.overdue::text from col`,[insurerId])
  ]);
  const k=kpis.rows[0]||{quotes:"0",accepted:"0",policies:"0",billed:"0",paid:"0",overdue:"0"}; const quoteCount=Number(k.quotes); const policyCount=Number(k.policies); const billed=Number(k.billed); const paid=Number(k.paid);
  const commercial=monthly.rows.map(x=>({label:monthLabel(x.label),primary:Number(x.quotes),secondary:Number(x.policies)})); const collections=collection.rows.map(x=>({label:monthLabel(x.label),primary:Number(x.billed),secondary:Number(x.paid)}));
  return <AdminPage eyebrow="Indicadores ejecutivos" title={insurer.data?.nombre_comercial||"Mi aseguradora"} description="Monitorea producción, conversión y cobranza con información actualizada de tu operación.">
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<FileText/>} label="Cotizaciones" value={quoteCount.toLocaleString("es-EC")} detail={`${Number(k.accepted)} aceptadas`}/><Metric icon={<FileCheck2/>} label="Pólizas emitidas" value={policyCount.toLocaleString("es-EC")} detail="Emisiones acumuladas"/><Metric icon={<Percent/>} label="Conversión" value={percentage(policyCount,quoteCount)} detail="Pólizas / cotizaciones"/><Metric icon={<DollarSign/>} label="Eficiencia de cobro" value={percentage(paid,billed)} detail={`${money(paid)} recaudado`}/></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-2"><ChartPanel title="Cotizaciones vs. emisiones" description="Evolución de los últimos seis meses"><ComparisonChart data={commercial} primaryLabel="Cotizaciones" secondaryLabel="Pólizas emitidas"/></ChartPanel><ChartPanel title="Cobranza mensual" description="Valores facturados frente a valores efectivamente cobrados"><ComparisonChart data={collections} primaryLabel="Facturado" secondaryLabel="Cobrado" format="currency"/></ChartPanel></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.35fr]"><ChartPanel title="Estado de cotizaciones" description="Distribución del embudo comercial"><StatusChart data={statuses.rows.map(x=>({label:x.label,value:Number(x.value)}))}/></ChartPanel><div className="glass-panel grid gap-5 p-5 sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-amber-200/60">Atención de cartera</p><h2 className="mt-2 text-lg font-bold">Resumen de cobranza</h2></div><div className="grid gap-3 sm:grid-cols-3"><CollectionMetric label="Facturado" value={money(billed)}/><CollectionMetric label="Cobrado" value={money(paid)}/><CollectionMetric label="Vencido" value={money(Number(k.overdue))} alert={Number(k.overdue)>0}/></div><div className="rounded-2xl border border-white/10 bg-white/4 p-4"><div className="flex items-center justify-between gap-4 text-xs"><span className="font-semibold text-white/55">Avance de recaudación</span><span className="font-bold text-cyan-100">{percentage(paid,billed)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-cyan-300" style={{width:`${Math.min(100,billed?paid/billed*100:0)}%`}}/></div></div></div></section>
    <section className="glass-panel mt-4 overflow-hidden"><header className="flex items-center justify-between border-b border-white/10 p-5 sm:p-6"><div><h2 className="font-bold">Cotizaciones recientes</h2><p className="mt-1 text-xs text-white/45">Actividad más reciente de tu aseguradora</p></div><Link href="/aseguradora/operacion" className="flex min-h-11 items-center gap-2 text-sm font-bold text-cyan-100">Ver operación <ArrowRight className="size-4"/></Link></header><div className="divide-y divide-white/8">{(recent.data||[]).map(x=><div key={x.id} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="font-semibold">{relationName(x.cliente,"nombre_razon_social")}</p><p className="mt-1 text-xs text-white/42">{relationName(x.producto,"nombre")} · {new Date(x.creado_en).toLocaleDateString("es-EC")}</p></div><p className="text-sm font-bold">{money(Number(x.cuota_fija_mensual))} <span className="ml-2 text-xs text-cyan-100/70">{x.estado}</span></p></div>)}{!recent.data?.length&&<p className="p-6 text-sm text-white/50">Todavía no existen cotizaciones.</p>}</div></section>
  </AdminPage>;
}

function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <article className="glass-panel min-w-0 p-5"><span className="text-cyan-100 [&_svg]:size-5">{icon}</span><p className="mt-7 break-words text-3xl font-bold tracking-[-0.04em]">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.12em] text-white/42">{label}</p><p className="mt-2 text-xs text-white/38">{detail}</p></article>}
function ChartPanel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="glass-panel min-w-0 p-5 sm:p-6"><header className="mb-6"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-white/45">{description}</p></header>{children}</section>}
function CollectionMetric({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <article className={`min-w-0 rounded-2xl border p-4 ${alert?"border-amber-200/20 bg-amber-200/8":"border-white/10 bg-white/4"}`}><div className="flex items-center gap-2">{alert&&<TriangleAlert className="size-4 text-amber-200"/>}<p className="text-[10px] font-bold uppercase tracking-wider text-white/42">{label}</p></div><p className="mt-3 break-words text-xl font-bold">{value}</p></article>}
function percentage(value:number,total:number){return total?`${(value/total*100).toLocaleString("es-EC",{maximumFractionDigits:1})}%`:"0%"}function money(value:number){return new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(value)}function monthLabel(value:string){const map:Record<string,string>={Jan:"Ene",Feb:"Feb",Mar:"Mar",Apr:"Abr",May:"May",Jun:"Jun",Jul:"Jul",Aug:"Ago",Sep:"Sep",Oct:"Oct",Nov:"Nov",Dec:"Dic"};return map[value]||value}function relationName(value:unknown,key:string){const row=Array.isArray(value)?value[0]:value;return row&&typeof row==="object"&&key in row?String((row as Record<string,unknown>)[key]):"—"}
