"use client";

import { useActionState } from "react";
import { LoaderCircle, Save } from "lucide-react";
import { assignSubscription, saveCatalogItem, saveInsurer, saveInsurerAdmin, savePlan } from "@/app/actions/platform";
import { initialPlatformState } from "@/lib/platform/action-state";

const input="min-h-11 w-full rounded-xl border border-white/15 bg-[#061323]/65 px-3.5 text-sm text-white outline-none placeholder:text-white/30 focus:border-cyan-100/55 [color-scheme:dark]";

export function InsurerForm({item}:{item?:{id:string;nombre_comercial:string;razon_social:string;ruc:string;logo_url:string|null}}){const[state,action,pending]=useActionState(saveInsurer,initialPlatformState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nombre comercial"><input name="commercialName" required defaultValue={item?.nombre_comercial} className={input}/></Field><Field label="Razón social"><input name="legalName" required defaultValue={item?.razon_social} className={input}/></Field><Field label="RUC"><input name="ruc" required inputMode="numeric" pattern="[0-9]{13}" defaultValue={item?.ruc} className={input}/></Field><Field label="URL del logotipo (opcional)"><input name="logoUrl" type="url" defaultValue={item?.logo_url||""} className={input}/></Field></Grid></Form>}

export function PlanForm({branches,item}:{branches:{id:string;nombre:string}[];item?:{id:string;nombre:string;descripcion:string|null;max_ramos:number|null;precio_mensual:number|string|null;branchIds:string[]}}){const[state,action,pending]=useActionState(savePlan,initialPlatformState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nombre"><input name="name" required defaultValue={item?.nombre} className={input}/></Field><Field label="Precio mensual"><input name="price" type="number" min="0" step="0.01" required defaultValue={item?.precio_mensual??0} className={input}/></Field><Field label="Máximo de ramos"><input name="maxBranches" type="number" min="1" defaultValue={item?.max_ramos??""} placeholder="Vacío = ilimitado" className={input}/></Field><Field label="Descripción"><input name="description" defaultValue={item?.descripcion||""} className={input}/></Field></Grid><fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[0.1em] text-white/48">Ramos habilitados</legend><div className="flex flex-wrap gap-2">{branches.map(branch=><label key={branch.id} className="flex min-h-10 cursor-pointer items-center gap-2 rounded-full border border-white/12 bg-white/5 px-3 text-xs font-semibold"><input type="checkbox" name="branchIds" value={branch.id} defaultChecked={item?.branchIds.includes(branch.id)??true} className="accent-cyan-200"/>{branch.nombre}</label>)}</div></fieldset></Form>}

type CatalogKind="ciudad"|"ramo"|"cobertura"|"clausula"|"deducible";
export function CatalogForm({kind,item}:{kind:CatalogKind;item?:{id:string;name:string;description?:string|null;province?:string|null;calculationType?:string}}){const bound=saveCatalogItem.bind(null,kind);const[state,action,pending]=useActionState(bound,initialPlatformState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label={kind==="clausula"?"Título":"Nombre"}><input name="name" required defaultValue={item?.name} className={input}/></Field>{kind==="ciudad"&&<Field label="Provincia"><input name="province" defaultValue={item?.province||""} className={input}/></Field>}{kind!=="ciudad"&&<Field label={kind==="clausula"?"Texto genérico":"Descripción"}><textarea name="description" required={kind==="clausula"} defaultValue={item?.description||""} rows={kind==="clausula"?3:1} className={`${input} py-3`}/></Field>}{kind==="deducible"&&<Field label="Tipo de cálculo"><select name="calculationType" defaultValue={item?.calculationType||"PORCENTAJE"} className={input}><option value="PORCENTAJE">Porcentaje</option><option value="VALOR_FIJO">Valor fijo</option></select></Field>}</Grid></Form>}

export function InsurerAdminForm({insurers,item}:{insurers:{id:string;nombre_comercial:string}[];item?:{id:string;nombre:string;email:string;aseguradora_id:string}}){const[state,action,pending]=useActionState(saveInsurerAdmin,initialPlatformState);return <Form action={action} state={state} pending={pending}><input type="hidden" name="id" value={item?.id||""}/><Grid><Field label="Nombre"><input name="name" required defaultValue={item?.nombre} autoComplete="name" className={input}/></Field><Field label="Correo"><input name="email" type="email" required defaultValue={item?.email} autoComplete="email" className={input}/></Field><Field label="Aseguradora"><select name="insurerId" required defaultValue={item?.aseguradora_id||""} className={input}><option value="">Selecciona</option>{insurers.map(x=><option key={x.id} value={x.id}>{x.nombre_comercial}</option>)}</select></Field><Field label={item?"Nueva contraseña (opcional)":"Contraseña temporal"}><input name="password" type="password" minLength={10} required={!item} autoComplete="new-password" className={input}/></Field></Grid></Form>}

export function SubscriptionForm({insurers,plans}:{insurers:{id:string;nombre_comercial:string}[];plans:{id:string;nombre:string}[]}){const[state,action,pending]=useActionState(assignSubscription,initialPlatformState);return <Form action={action} state={state} pending={pending}><Grid><Field label="Aseguradora"><select name="insurerId" required className={input}><option value="">Selecciona</option>{insurers.map(x=><option key={x.id} value={x.id}>{x.nombre_comercial}</option>)}</select></Field><Field label="Plan"><select name="planId" required className={input}><option value="">Selecciona</option>{plans.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field><Field label="Fecha de inicio"><input name="startDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={input}/></Field><Field label="Fecha de fin (opcional)"><input name="endDate" type="date" className={input}/></Field></Grid></Form>}

function Form({action,state,pending,children}:{action:(formData:FormData)=>void;state:{status:string;message?:string};pending:boolean;children:React.ReactNode}){return <form action={action} className="grid gap-4">{state.message&&<p className={`rounded-xl border px-4 py-3 text-sm ${state.status==="success"?"border-emerald-300/25 bg-emerald-300/10 text-emerald-50":"border-red-300/25 bg-red-300/10 text-red-50"}`}>{state.message}</p>}{children}<button disabled={pending} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-[#071426] hover:opacity-90 disabled:opacity-60 sm:justify-self-end">{pending?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}{pending?"Guardando…":"Guardar"}</button></form>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-[0.1em] text-white/48">{label}</span>{children}</label>}
