import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CalendarDays, CarFront, ScanLine, ShieldCheck, TrendingUp } from "lucide-react";
import { requireChannelUser } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { isCarroceria, requiredSlots } from "@/lib/inspeccion/slots";

export const metadata:Metadata={title:"Detalle de cotización | Arkad",robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{created?:string}>}){
  const session=await requireChannelUser(); const {id}=await params; const query=await searchParams; const db=createAdminClient();
  const {data:quote}=await db.from("cotizacion").select("id,creado_en,estado,anios_vigencia,fecha_inicio_vigencia,fecha_fin_vigencia,total_dias,tasa_promedio,nivel_riesgo,cuota_fija_mensual,cliente(nombre_razon_social,identificacion,email),producto(nombre),vehiculo(marca,modelo,anio,color,valor_asegurado,placa),usuario(nombre),inspeccion(carroceria,estado,inspeccion_foto(count))").eq("id",id).eq("canal_id",session.channelId!).maybeSingle();
  if(!quote)redirect("/canal/cotizaciones");
  const inspeccionBadge=inspectionBadge(quote.inspeccion);
  const {data:schedule}=await db.from("amortizacion_mensual").select("mes,valor_asegurado_mes,prima_total_mes,cuota_fija").eq("cotizacion_id",id).order("mes");
  const vehicle=first(quote.vehiculo),client=first(quote.cliente);
  return <main className="relative z-10 mx-auto w-full max-w-[1120px] px-4 py-8 sm:px-7 lg:px-10"><Link href="/canal/cotizaciones" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-white/60"><ArrowLeft className="size-4"/>Cotizaciones</Link>{query.created==="1"&&<p className="mt-3 rounded-xl border border-emerald-300/25 bg-emerald-300/10 px-4 py-3 text-sm">Cotización asistida calculada y guardada correctamente.</p>}<header className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-cyan-100/65">{client?.nombre_razon_social}</p><h1 className="mt-2 text-4xl font-bold tracking-[-0.035em]">{vehicle?.marca} {vehicle?.modelo}</h1><p className="mt-2 text-sm text-white/55">{rel(quote.producto,"nombre")} · Agente {rel(quote.usuario,"nombre")}</p></div><div className="flex flex-wrap items-center gap-2"><Link href={`/canal/cotizaciones/${id}/inspeccion`} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-cyan-100/25 bg-cyan-100/10 px-4 text-xs font-bold uppercase tracking-wider text-cyan-50 hover:bg-cyan-100/16"><ScanLine className="size-4"/> Inspección{inspeccionBadge?` · ${inspeccionBadge}`:""}</Link><span className="w-fit rounded-full border border-cyan-100/20 bg-cyan-100/10 px-4 py-2 text-xs font-bold">{quote.estado}</span></div></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<ShieldCheck/>} label="Cuota mensual" value={money(quote.cuota_fija_mensual)}/><Metric icon={<TrendingUp/>} label="Tasa promedio" value={`${(Number(quote.tasa_promedio)*100).toFixed(3)}%`}/><Metric icon={<ShieldCheck/>} label="Riesgo" value={quote.nivel_riesgo===1?"Alto":quote.nivel_riesgo===2?"Moderado":"Bajo"}/><Metric icon={<CalendarDays/>} label="Cuotas" value={String(quote.anios_vigencia*12)}/></section>
    <section className="glass-panel mt-4 p-5"><h2 className="flex items-center gap-2 font-bold"><CalendarDays className="size-5 text-cyan-100"/>Vigencia de cobertura</h2><dl className="mt-5 grid gap-4 sm:grid-cols-3"><Detail label="Fecha de inicio" value={date(quote.fecha_inicio_vigencia)}/><Detail label="Fecha de finalización" value={date(quote.fecha_fin_vigencia)}/><Detail label="Total de días" value={String(quote.total_dias||0)}/></dl></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2"><article className="glass-panel p-5"><h2 className="flex items-center gap-2 font-bold"><CarFront className="size-5 text-cyan-100"/>Vehículo</h2><dl className="mt-5 grid grid-cols-2 gap-4"><Detail label="Año" value={String(vehicle?.anio||"—")}/><Detail label="Color" value={vehicle?.color||"—"}/><Detail label="Valor" value={money(vehicle?.valor_asegurado||0)}/><Detail label="Placa" value={vehicle?.placa||"—"}/></dl></article><article className="glass-panel p-5"><h2 className="font-bold">Cliente</h2><dl className="mt-5 grid gap-4"><Detail label="Identificación" value={client?.identificacion||"—"}/><Detail label="Correo" value={client?.email||"—"}/></dl></article></section>
    <section className="glass-panel mt-4 overflow-hidden"><header className="p-5"><h2 className="font-bold">Proyección mensual</h2><p className="mt-1 text-xs text-white/45">{schedule?.length||0} períodos completos, sin prorrateos.</p></header><div className="grid divide-y divide-white/8 md:hidden">{(schedule||[]).map(row=><div key={row.mes} className="grid grid-cols-2 gap-2 p-4 text-xs"><span>Mes {row.mes}</span><strong className="text-right">{money(row.cuota_fija)}</strong><span className="text-white/45">Valor asegurado</span><span className="text-right text-white/60">{money(row.valor_asegurado_mes)}</span></div>)}</div><div className="hidden max-h-[500px] overflow-auto md:block"><table className="w-full text-sm"><thead className="sticky top-0 bg-[#071426]"><tr><th className="p-3 text-left">Mes</th><th className="p-3 text-left">Valor asegurado</th><th className="p-3 text-left">Costo real</th><th className="p-3 text-right">Cuota</th></tr></thead><tbody>{(schedule||[]).map(row=><tr key={row.mes} className="border-t border-white/8"><td className="p-3">{row.mes}</td><td className="p-3">{money(row.valor_asegurado_mes)}</td><td className="p-3">{money(row.prima_total_mes)}</td><td className="p-3 text-right font-bold">{money(row.cuota_fija)}</td></tr>)}</tbody></table></div></section>
  </main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article className="glass-panel p-5"><span className="text-cyan-100 [&_svg]:size-5">{icon}</span><p className="mt-5 text-[10px] font-bold uppercase text-white/42">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></article>}
function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] font-bold uppercase text-white/38">{label}</dt><dd className="mt-1 text-sm">{value}</dd></div>}
function first<T>(value:T|T[]|null){return Array.isArray(value)?value[0]||null:value}function rel(value:unknown,key:string){const row=Array.isArray(value)?value[0]:value;return row&&typeof row==="object"&&key in row?String((row as Record<string,unknown>)[key]):"—"}function money(value:number|string){return new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(Number(value))}function date(value:string|null){return value?new Intl.DateTimeFormat("es-EC",{dateStyle:"long",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`)):"—"}
function inspectionBadge(value:unknown):string|null{const row=first(value as {carroceria?:string;estado?:string;inspeccion_foto?:{count:number}[]}|null);if(!row||!isCarroceria(row.carroceria))return null;if(row.estado==="COMPLETADA")return "Completada";const count=Array.isArray(row.inspeccion_foto)?row.inspeccion_foto[0]?.count??0:0;return `${count}/${requiredSlots(row.carroceria).length}`}
